/**
 * Dependency-aware scheduling for pipeline steps.
 *
 * Golden rules:
 *  - Pipeline order tells us the *possible* execution order.
 *  - Dependency tells us whether an agent must wait.
 *  - "Unknown / ambiguous dependency" NEVER means independent.
 *    When in doubt, the edge stays and execution remains sequential
 *    (byte-for-byte the pre-existing behavior).
 *
 * Decision hierarchy (spec §5):
 *  1. Explicit per-step dependsOn                → use exactly (unsatisfiable refs → warning, never wait-forever)
 *  2. Agent artifact contract (requires/produces) → keep edges to producers of required artifacts
 *  3. Built-in executor behavior (real code paths in agentExecutor.js)
 *  4. System-prompt signals / planner LLM        → may only CUT baseline edges when confident
 *  5. Otherwise                                  → depend on all previous steps (sequential)
 */

import { askLLM, isLlmConfigured } from "../services/llmService.js";
import { logger } from "../utils/logger.js";

// ─────────────────────────────────────────────────────────────
// Signal D: behavior of the built-in executors, derived from the
// actual data flow in agentExecutor.js (NOT from names for
// scheduling — these document what each executor truly consumes).
// Any *other* agent producing the same artifact satisfies the need.
// ─────────────────────────────────────────────────────────────
const EXECUTOR_BEHAVIOR = {
  // executeResearcher: reads context.input + own tool results only.
  researcher: { produces: ["research", "content"], requires: [], softRequires: true },
  // executeWriter: injects getResearchContext() (research artifact when present;
  // graceful fallback note when absent → research is a SOFT requirement).
  writer: { produces: ["draft", "content"], requires: ["research"], softRequires: true },
  // executeEditor: getDraftForReview() → writer draft, else latest text output.
  // Wants the nearest prior content artifact (its review target).
  editor: { produces: ["review"], requires: ["draft", "content"], nearestContent: true }
};

// Artifact labels that count as "reviewable content" for the editor fallback.
const CONTENT_TOKENS = new Set(["draft", "content", "research", "analysis", "report", "summary", "article", "translation"]);

// Signal C: prompt hints (never the ONLY source of truth — combined with the rest).
const DEPENDENCY_HINTS = [
  /previous agent/i, /\bprior agent/i, /previous output/i, /prior output/i,
  /previous agent'?s output/i, /output(s)? (of|from) (the )?(previous|prior)/i,
  /\bthe draft\b/i, /\bthe research\b/i, /\bthe findings\b/i,
  /improve the (content|draft|text)/i, /revise the (content|draft)/i,
  /review the (content|draft|research|output|findings)/i,
  /verify the claims in/i, /translate the (article|content|draft)/i,
  /based on the (previous|prior|research|draft|findings)/i,
  /provided by (the )?(previous|prior)/i, /generated by (the )?(previous|prior)/i,
  /summari[sz]e the (previous|prior|provided|above)/i
];

const INDEPENDENCE_HINTS = [
  /\bindependent(ly)?\b/i, /original (user )?input only/i, /only the original (user )?(input|request|topic)/i,
  /does not (require|need|depend)/i, /from (your|its) own knowledge/i,
  /ignore (the )?(previous|prior)/i, /without (using )?(the )?(previous|prior)/i,
  /as the primary input/i
];

function detectPromptSignals(systemPrompt = "") {
  const text = String(systemPrompt || "");
  return {
    dependency: DEPENDENCY_HINTS.some((rx) => rx.test(text)),
    independence: INDEPENDENCE_HINTS.some((rx) => rx.test(text))
  };
}

// ─────────────────────────────────────────────────────────────
// Contracts
// ─────────────────────────────────────────────────────────────

function normalizeArtifactList(value) {
  if (!Array.isArray(value)) return null;
  const list = value
    .map((entry) => String(entry || "").trim().toLowerCase())
    .filter(Boolean)
    .slice(0, 8);
  return list;
}

/**
 * Returns an artifact contract for a step, or null when the agent's
 * data needs are unknown (→ conservative sequential handling).
 * Known sources: built-in executor behavior, or a custom agent's
 * declared requires/produces fields.
 */
export function getStepContract(step) {
  if (!step) return null;

  if (step.type === "built-in" && EXECUTOR_BEHAVIOR[step.agentId]) {
    return { ...EXECUTOR_BEHAVIOR[step.agentId], source: "executor-behavior" };
  }

  const declaredRequires = normalizeArtifactList(step.requires);
  const declaredProduces = typeof step.produces === "string" && step.produces.trim()
    ? [step.produces.trim().toLowerCase()]
    : null;

  if (declaredRequires || declaredProduces) {
    return {
      requires: declaredRequires || [],
      produces: declaredProduces || [step.phase === "custom" ? "content" : step.phase || "content"],
      source: "declared-contract"
    };
  }

  return null;
}

function defaultProduces(step) {
  const contract = getStepContract(step);
  if (contract?.produces?.length) return contract.produces;
  return [step?.phase === "review" ? "review" : "content"];
}

// ─────────────────────────────────────────────────────────────
// Reference resolution
// ─────────────────────────────────────────────────────────────

function buildStepIndexes(steps) {
  const byStepId = new Map();
  const byAgentId = new Map();
  for (const step of steps) {
    byStepId.set(step.stepId, step);
    if (!byAgentId.has(step.agentId)) byAgentId.set(step.agentId, step);
  }
  return { byStepId, byAgentId };
}

function resolveRef(ref, indexes) {
  const id = String(ref || "").trim();
  if (!id) return null;
  if (indexes.byStepId.has(id)) return indexes.byStepId.get(id);
  if (indexes.byAgentId.has(id)) return indexes.byAgentId.get(id);
  return null;
}

// ─────────────────────────────────────────────────────────────
// Planner (LLM) — signal C refinement.
// May ONLY narrow the conservative baseline for steps whose needs
// are otherwise unknown. Never adds edges beyond the baseline,
// never cuts a contract/executor-kept edge. Cached per run config
// so repeated runs / loop iterations never duplicate LLM calls.
// ─────────────────────────────────────────────────────────────

const plannerCache = new Map();

function plannerCacheKey(descriptors) {
  return JSON.stringify(descriptors);
}

function buildPlannerPrompt(descriptors) {
  const block = descriptors
    .map((d) =>
      `stepId: ${d.stepId}\nname: ${d.name}\nrole: ${d.role || ""}\nphase: ${d.phase}\npriorSteps: ${d.priorStepIds.join(", ") || "none"}\nsystemPrompt: """${(d.systemPrompt || "").slice(0, 800)}"""`
    )
    .join("\n---\n");

  return `You are a dependency analyzer for a multi-agent pipeline.

For EACH step below, decide which of its PRIOR steps it truly must wait for — i.e. which prior outputs it actually consumes as input.

Rules:
- The original user input is always available to every step and NEVER creates a dependency.
- Tool access never creates a dependency on another agent.
- If a step can fully do its job from the original input alone, it depends on NO prior step.
- If unsure or ambiguous, INCLUDE the prior step (conservative: waiting is safe, missing data is not).
- Order alone does not imply dependency.
- Confidence "high" or "medium" only when clear; use "low" when guessing (treated as dependent).

Return ONLY valid JSON:
{"dependencies":[{"stepId":"<id>","dependsOn":["<prior stepId>", ...],"confidence":"high|medium|low","reason":"short"}]}

STEPS:
${block}`;
}

async function askPlanner(steps) {
  const ambiguous = steps.filter((step) => {
    if (Array.isArray(step.dependsOn)) return false;       // explicit → planner not needed
    if (getStepContract(step)) return false;               // contract/executor known → handled
    return true;                                           // unknown needs → planner may narrow
  });

  if (!ambiguous.length) return new Map();
  if (!isLlmConfigured()) return new Map();

  const descriptors = steps.map((step, index) => ({
    stepId: step.stepId,
    name: step.name,
    role: step.role,
    phase: step.phase,
    systemPrompt: step.agent?.systemPrompt || step.systemPrompt || "",
    priorStepIds: steps.slice(0, index).map((s) => s.stepId)
  }));

  const key = plannerCacheKey(descriptors);
  if (plannerCache.has(key)) return plannerCache.get(key);

  const result = new Map();
  try {
    const raw = await askLLM(buildPlannerPrompt(descriptors), {
      temperature: 0.1,
      jsonMode: true,
      systemMessage: "You analyze pipeline dependencies. Return only valid JSON. Be conservative: when unsure, keep the dependency."
    });

    const parsed = raw ? JSON.parse(raw) : null;
    const entries = Array.isArray(parsed?.dependencies) ? parsed.dependencies : [];

    for (const entry of entries) {
      const stepId = String(entry?.stepId || "");
      if (!stepId || !ambiguous.some((s) => s.stepId === stepId)) continue;
      const confidence = String(entry?.confidence || "low").toLowerCase();
      if (confidence !== "high" && confidence !== "medium") continue; // low → keep baseline
      const dependsOn = Array.isArray(entry.dependsOn)
        ? entry.dependsOn.map((d) => String(d || "").trim()).filter(Boolean)
        : null;
      if (!dependsOn) continue;
      result.set(stepId, { dependsOn, reason: String(entry?.reason || "planner") });
    }
  } catch (error) {
    logger.warning(`Dependency planner unavailable (${error.message}). Ambiguous steps stay sequential.`);
  }

  plannerCache.set(key, result);
  return result;
}

// ─────────────────────────────────────────────────────────────
// Edge resolution
// ─────────────────────────────────────────────────────────────

function resolveStepDependencies(step, index, steps, indexes, plannerAnswers, warnings, reasons) {
  const priorSteps = steps.slice(0, index);
  const priorIds = priorSteps.map((s) => s.stepId);

  // ── Signal A: explicit dependsOn (exact override) ──
  if (Array.isArray(step.dependsOn)) {
    const edges = [];
    for (const ref of step.dependsOn) {
      const target = resolveRef(ref, indexes);
      if (!target) {
        warnings.push({
          stepId: step.stepId,
          dependency: String(ref),
          warning: `Unsatisfied dependency "${ref}": no such step in this pipeline. Not waiting for it (fail-fast, no deadlock).`
        });
        continue;
      }
      if (target.stepId === step.stepId) continue;
      if (!priorIds.includes(target.stepId)) {
        // Reference to a LATER step: honoring it would invert the pipeline's
        // declared order (and risks cycles). Treat as unsatisfied — warn, never wait.
        warnings.push({
          stepId: step.stepId,
          dependency: String(ref),
          warning: `Dependency "${ref}" refers to a later step in this pipeline. Execution order follows the declared pipeline order; not waiting for it.`
        });
        continue;
      }
      if (!edges.includes(target.stepId)) edges.push(target.stepId);
    }
    reasons[step.stepId] = edges.length
      ? `explicit dependsOn → ${edges.join(", ")}`
      : "explicit dependsOn [] → independent (original input only)";
    return edges;
  }

  const contract = getStepContract(step);

  // ── Signals B + D: artifact contract / executor behavior ──
  if (contract) {
    const requires = contract.requires || [];

    if (!requires.length) {
      reasons[step.stepId] = `contract (${contract.source}): requires nothing → independent`;
      return [];
    }

    const edges = [];
    for (const prior of priorSteps) {
      const produces = defaultProduces(prior);
      if (produces.some((p) => requires.includes(p))) {
        edges.push(prior.stepId);
      }
    }

    // Editor-style "nearest prior content" fallback:
    // wants the latest content artifact, whatever produced it in THIS pipeline.
    if (!edges.length && contract.nearestContent && priorSteps.length) {
      for (let i = priorSteps.length - 1; i >= 0; i -= 1) {
        const prior = priorSteps[i];
        const produces = defaultProduces(prior);
        if (produces.some((p) => CONTENT_TOKENS.has(p)) || prior.type !== "built-in") {
          edges.push(prior.stepId);
          break;
        }
      }
      if (!edges.length) edges.push(priorSteps[priorSteps.length - 1].stepId);
    }

    reasons[step.stepId] = edges.length
      ? `contract (${contract.source}): requires [${requires.join(", ")}] → waits for ${edges.join(", ")}`
      : `contract (${contract.source}): requires [${requires.join(", ")}] but no producer in pipeline → runs without it`;
    return edges;
  }

  // ── Signal C: planner LLM (may only narrow the baseline) ──
  const planner = plannerAnswers.get(step.stepId);
  if (planner) {
    const edges = [];
    for (const ref of planner.dependsOn) {
      const target = resolveRef(ref, indexes);
      if (target && priorIds.includes(target.stepId) && !edges.includes(target.stepId)) {
        edges.push(target.stepId);
      }
    }
    reasons[step.stepId] = `planner: ${planner.reason} → ${edges.length ? edges.join(", ") : "independent"}`;
    return edges;
  }

  // ── Prompt hints (offline safety net): explicit independence and
  //    zero dependency hints allow narrowing; anything else stays. ──
  const signals = detectPromptSignals(step.agent?.systemPrompt || step.systemPrompt || "");
  if (signals.independence && !signals.dependency) {
    reasons[step.stepId] = "prompt signals: independent, no dependency hints → independent";
    return [];
  }

  // ── Rule 6: ambiguous / unknown → sequential (baseline) ──
  reasons[step.stepId] = "needs unknown → conservative: depends on all previous steps";
  return priorIds;
}

// ─────────────────────────────────────────────────────────────
// Level building (Kahn topological sort, cycle-safe)
// ─────────────────────────────────────────────────────────────

export function buildExecutionLevels(orderedStepIds, edgesByStepId) {
  const remainingDeps = new Map();
  for (const stepId of orderedStepIds) {
    const deps = (edgesByStepId.get(stepId) || []).filter((d) => orderedStepIds.includes(d));
    remainingDeps.set(stepId, new Set(deps));
  }

  const levels = [];
  const placed = new Set();

  while (placed.size < orderedStepIds.length) {
    const ready = orderedStepIds.filter(
      (stepId) => !placed.has(stepId) && remainingDeps.get(stepId).size === 0
    );

    if (!ready.length) {
      // Cycle → never deadlock: degrade to strict sequential.
      logger.warning("Dependency cycle detected → falling back to sequential execution for safety.");
      const rest = orderedStepIds.filter((stepId) => !placed.has(stepId));
      return {
        levels: [...levels, ...rest.map((stepId) => [stepId])],
        cycleDetected: true
      };
    }

    levels.push(ready);
    for (const stepId of ready) {
      placed.add(stepId);
      for (const [, deps] of remainingDeps) deps.delete(stepId);
    }
  }

  return { levels, cycleDetected: false };
}

// ─────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────

/**
 * Analyze a list of steps and return the execution schedule.
 * Pure scheduling data — does not execute anything.
 */
export async function computeSchedule(steps) {
  const indexes = buildStepIndexes(steps);
  const plannerAnswers = await askPlanner(steps);

  const edgesByStepId = new Map();
  const warnings = [];
  const reasons = {};

  steps.forEach((step, index) => {
    const edges = resolveStepDependencies(step, index, steps, indexes, plannerAnswers, warnings, reasons);
    edgesByStepId.set(step.stepId, edges);
  });

  const orderedIds = steps.map((s) => s.stepId);
  const { levels, cycleDetected } = buildExecutionLevels(orderedIds, edgesByStepId);

  if (cycleDetected) {
    warnings.push({ warning: "Dependency cycle detected; fell back to sequential execution." });
  }

  return {
    levels,                        // [[stepId, ...], ...] — each inner array runs in parallel
    edges: Object.fromEntries([...edgesByStepId.entries()]),
    reasons,                       // stepId → human-readable why (dashboard transparency)
    warnings,
    parallel: levels.some((level) => level.length > 1),
    plannerUsed: plannerAnswers.size > 0
  };
}

/**
 * Convenience for pipeline slices (pre-loop / loop / post-loop steps).
 * Deps pointing outside the slice are treated as already satisfied.
 */
export async function planSliceLevels(steps) {
  const schedule = await computeSchedule(steps);
  return schedule.levels;
}
